// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: books-app/internal/pkg/proto/book.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

type AddBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookResponse) Reset() {
	*x = AddBookResponse{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookResponse) ProtoMessage() {}

func (x *AddBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookResponse.ProtoReflect.Descriptor instead.
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{2}
}

func (x *AddBookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListBooksRespose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRespose) Reset() {
	*x = ListBooksRespose{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRespose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRespose) ProtoMessage() {}

func (x *ListBooksRespose) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRespose.ProtoReflect.Descriptor instead.
func (*ListBooksRespose) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{3}
}

func (x *ListBooksRespose) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookRequest) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

type RemoveBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBookRequest) Reset() {
	*x = RemoveBookRequest{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookRequest) ProtoMessage() {}

func (x *RemoveBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookRequest.ProtoReflect.Descriptor instead.
func (*RemoveBookRequest) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveBookRequest) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

type RemoveBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBookResponse) Reset() {
	*x = RemoveBookResponse{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookResponse) ProtoMessage() {}

func (x *RemoveBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookResponse.ProtoReflect.Descriptor instead.
func (*RemoveBookResponse) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveBookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviewer      string                 `protobuf:"bytes,1,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{8}
}

func (x *Review) GetReviewer() string {
	if x != nil {
		return x.Reviewer
	}
	return ""
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type SubmitReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Reviewer      string                 `protobuf:"bytes,2,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewRequest) Reset() {
	*x = SubmitReviewRequest{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewRequest) ProtoMessage() {}

func (x *SubmitReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitReviewRequest) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitReviewRequest) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

func (x *SubmitReviewRequest) GetReviewer() string {
	if x != nil {
		return x.Reviewer
	}
	return ""
}

func (x *SubmitReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SubmitReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type SubmitReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewResponse) Reset() {
	*x = SubmitReviewResponse{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewResponse) ProtoMessage() {}

func (x *SubmitReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitReviewResponse) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitReviewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetBookReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookReviewsRequest) Reset() {
	*x = GetBookReviewsRequest{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookReviewsRequest) ProtoMessage() {}

func (x *GetBookReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetBookReviewsRequest) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{11}
}

func (x *GetBookReviewsRequest) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

type GetBookReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookReviewsResponse) Reset() {
	*x = GetBookReviewsResponse{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookReviewsResponse) ProtoMessage() {}

func (x *GetBookReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetBookReviewsResponse) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{12}
}

func (x *GetBookReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type GetBookInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookInfoRequest) Reset() {
	*x = GetBookInfoRequest{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookInfoRequest) ProtoMessage() {}

func (x *GetBookInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBookInfoRequest) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{13}
}

func (x *GetBookInfoRequest) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

type GetBookInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          int32                  `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Reviews       []*Review              `protobuf:"bytes,4,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookInfoResponse) Reset() {
	*x = GetBookInfoResponse{}
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookInfoResponse) ProtoMessage() {}

func (x *GetBookInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_app_internal_pkg_proto_book_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBookInfoResponse) Descriptor() ([]byte, []int) {
	return file_books_app_internal_pkg_proto_book_proto_rawDescGZIP(), []int{14}
}

func (x *GetBookInfoResponse) GetIsbn() int32 {
	if x != nil {
		return x.Isbn
	}
	return 0
}

func (x *GetBookInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBookInfoResponse) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *GetBookInfoResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_books_app_internal_pkg_proto_book_proto protoreflect.FileDescriptor

const file_books_app_internal_pkg_proto_book_proto_rawDesc = "" +
	"\n" +
	"'books-app/internal/pkg/proto/book.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"L\n" +
	"\x04Book\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\")\n" +
	"\x0fAddBookResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"5\n" +
	"\x10ListBooksRespose\x12!\n" +
	"\x05books\x18\x01 \x03(\v2\v.proto.BookR\x05books\"$\n" +
	"\x0eGetBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\"'\n" +
	"\x11RemoveBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\",\n" +
	"\x12RemoveBookResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\",\n" +
	"\x12UpdateBookResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"V\n" +
	"\x06Review\x12\x1a\n" +
	"\breviewer\x18\x01 \x01(\tR\breviewer\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"w\n" +
	"\x13SubmitReviewRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\x12\x1a\n" +
	"\breviewer\x18\x02 \x01(\tR\breviewer\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\".\n" +
	"\x14SubmitReviewResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"+\n" +
	"\x15GetBookReviewsRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\"A\n" +
	"\x16GetBookReviewsResponse\x12'\n" +
	"\areviews\x18\x01 \x03(\v2\r.proto.ReviewR\areviews\"(\n" +
	"\x12GetBookInfoRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\"\x84\x01\n" +
	"\x13GetBookInfoResponse\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\x05R\x04isbn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12'\n" +
	"\areviews\x18\x04 \x03(\v2\r.proto.ReviewR\areviews2\xa3\x02\n" +
	"\vBookService\x120\n" +
	"\aAddBook\x12\v.proto.Book\x1a\x16.proto.AddBookResponse\"\x00\x124\n" +
	"\tListBooks\x12\f.proto.Empty\x1a\x17.proto.ListBooksRespose\"\x00\x12/\n" +
	"\aGetBook\x12\x15.proto.GetBookRequest\x1a\v.proto.Book\"\x00\x12C\n" +
	"\n" +
	"RemoveBook\x12\x18.proto.RemoveBookRequest\x1a\x19.proto.RemoveBookResponse\"\x00\x126\n" +
	"\n" +
	"UpdateBook\x12\v.proto.Book\x1a\x19.proto.UpdateBookResponse\"\x002\xa8\x01\n" +
	"\rReviewService\x12H\n" +
	"\rSubmitReviews\x12\x1a.proto.SubmitReviewRequest\x1a\x1b.proto.SubmitReviewResponse\x12M\n" +
	"\x0eGetBookReviews\x12\x1c.proto.GetBookReviewsRequest\x1a\x1d.proto.GetBookReviewsResponse2b\n" +
	"\x0fBookInfoService\x12O\n" +
	"\x16GetBookInfoWithReviews\x12\x19.proto.GetBookInfoRequest\x1a\x1a.proto.GetBookInfoResponseB\tZ\a./protob\x06proto3"

var (
	file_books_app_internal_pkg_proto_book_proto_rawDescOnce sync.Once
	file_books_app_internal_pkg_proto_book_proto_rawDescData []byte
)

func file_books_app_internal_pkg_proto_book_proto_rawDescGZIP() []byte {
	file_books_app_internal_pkg_proto_book_proto_rawDescOnce.Do(func() {
		file_books_app_internal_pkg_proto_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_books_app_internal_pkg_proto_book_proto_rawDesc), len(file_books_app_internal_pkg_proto_book_proto_rawDesc)))
	})
	return file_books_app_internal_pkg_proto_book_proto_rawDescData
}

var file_books_app_internal_pkg_proto_book_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_books_app_internal_pkg_proto_book_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: proto.Empty
	(*Book)(nil),                   // 1: proto.Book
	(*AddBookResponse)(nil),        // 2: proto.AddBookResponse
	(*ListBooksRespose)(nil),       // 3: proto.ListBooksRespose
	(*GetBookRequest)(nil),         // 4: proto.GetBookRequest
	(*RemoveBookRequest)(nil),      // 5: proto.RemoveBookRequest
	(*RemoveBookResponse)(nil),     // 6: proto.RemoveBookResponse
	(*UpdateBookResponse)(nil),     // 7: proto.UpdateBookResponse
	(*Review)(nil),                 // 8: proto.Review
	(*SubmitReviewRequest)(nil),    // 9: proto.SubmitReviewRequest
	(*SubmitReviewResponse)(nil),   // 10: proto.SubmitReviewResponse
	(*GetBookReviewsRequest)(nil),  // 11: proto.GetBookReviewsRequest
	(*GetBookReviewsResponse)(nil), // 12: proto.GetBookReviewsResponse
	(*GetBookInfoRequest)(nil),     // 13: proto.GetBookInfoRequest
	(*GetBookInfoResponse)(nil),    // 14: proto.GetBookInfoResponse
}
var file_books_app_internal_pkg_proto_book_proto_depIdxs = []int32{
	1,  // 0: proto.ListBooksRespose.books:type_name -> proto.Book
	8,  // 1: proto.GetBookReviewsResponse.reviews:type_name -> proto.Review
	8,  // 2: proto.GetBookInfoResponse.reviews:type_name -> proto.Review
	1,  // 3: proto.BookService.AddBook:input_type -> proto.Book
	0,  // 4: proto.BookService.ListBooks:input_type -> proto.Empty
	4,  // 5: proto.BookService.GetBook:input_type -> proto.GetBookRequest
	5,  // 6: proto.BookService.RemoveBook:input_type -> proto.RemoveBookRequest
	1,  // 7: proto.BookService.UpdateBook:input_type -> proto.Book
	9,  // 8: proto.ReviewService.SubmitReviews:input_type -> proto.SubmitReviewRequest
	11, // 9: proto.ReviewService.GetBookReviews:input_type -> proto.GetBookReviewsRequest
	13, // 10: proto.BookInfoService.GetBookInfoWithReviews:input_type -> proto.GetBookInfoRequest
	2,  // 11: proto.BookService.AddBook:output_type -> proto.AddBookResponse
	3,  // 12: proto.BookService.ListBooks:output_type -> proto.ListBooksRespose
	1,  // 13: proto.BookService.GetBook:output_type -> proto.Book
	6,  // 14: proto.BookService.RemoveBook:output_type -> proto.RemoveBookResponse
	7,  // 15: proto.BookService.UpdateBook:output_type -> proto.UpdateBookResponse
	10, // 16: proto.ReviewService.SubmitReviews:output_type -> proto.SubmitReviewResponse
	12, // 17: proto.ReviewService.GetBookReviews:output_type -> proto.GetBookReviewsResponse
	14, // 18: proto.BookInfoService.GetBookInfoWithReviews:output_type -> proto.GetBookInfoResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_books_app_internal_pkg_proto_book_proto_init() }
func file_books_app_internal_pkg_proto_book_proto_init() {
	if File_books_app_internal_pkg_proto_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_books_app_internal_pkg_proto_book_proto_rawDesc), len(file_books_app_internal_pkg_proto_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_books_app_internal_pkg_proto_book_proto_goTypes,
		DependencyIndexes: file_books_app_internal_pkg_proto_book_proto_depIdxs,
		MessageInfos:      file_books_app_internal_pkg_proto_book_proto_msgTypes,
	}.Build()
	File_books_app_internal_pkg_proto_book_proto = out.File
	file_books_app_internal_pkg_proto_book_proto_goTypes = nil
	file_books_app_internal_pkg_proto_book_proto_depIdxs = nil
}
